### ISSUE TITLE
I was searching for the sources too...

### ISSUE THREAD

**Issue by floriankraft** [farazkaleemmalik/lelelab-y2k-76-files#1]
I was searching for the sources of the Y2K as well and I might have found another repo where they do already exist:
https://github.com/theCommaLlama/qmk-firmware-lelelab-y2k-76

However, I did not receive the keyboard yet, so I can not confirm.

Also when searching through the official LeleLab Discord channel (https://discord.gg/FNSK6HyTYU) it seems that the developer seems to share the sources now (found a message from 1st of June).

My keyboard is on its way, so fingers crossed that the sources are right. 🙂 

PS: Sorry for opening an "issue" but it seems to be the only way to communicate this.

**Comment by numberisnan** [comment]
Sure. I messaged you on Discord. If you want to contact a developer on Github you should check their socials on their profile. My email is right there. I didn't even get a notification for this issue which is strange.
